"use client"

import { useState, useEffect } from "react"
import { Button } from "@/components/ui/button"
import { Download, Loader2 } from "lucide-react"
import { exportToPDF } from "@/lib/export-utils"
import type { ExportColumn } from "@/lib/export-utils"
import { toast } from "sonner"
import { logger } from "@/lib/logger"

interface ExportButtonProps {
  filename: string
  title: string
  subtitle?: string
  columns: ExportColumn[]
  data?: any[]
  /** Async fetch for full dataset (used when you don't pass data directly) */
  onExport?: () => Promise<any[]>
  onExportStart?: () => void
  onExportEnd?: () => void
  /** Name displayed as "Generated By" in the PDF header */
  generatedBy?: string
  /**
   * Key-value summary pairs shown in the summary band.
   * If omitted, auto-computed from data using status/count aggregation.
   */
  summary?: { label: string; value: string | number }[]
}

// ── Auto-summary builder ─────────────────────────────────────────────────────
/**
 * Scans export data and columns to build a sensible summary:
 * - Total record count
 * - Per-status counts (if a "status" column exists)
 * - Currency totals (if currency columns exist)
 */
function buildAutoSummary(
  data: any[],
  columns: ExportColumn[]
): { label: string; value: string | number }[] {
  const summary: { label: string; value: string | number }[] = []

  summary.push({ label: "Total Records", value: data.length })

  // Status distribution
  const statusCol = columns.find(c => c.type === "status" || c.dataKey === "status")
  if (statusCol) {
    const counts: Record<string, number> = {}
    data.forEach(row => {
      const val = String(row[statusCol.dataKey] || "unknown")
        .toLowerCase()
        .replace(/_/g, " ")
      counts[val] = (counts[val] || 0) + 1
    })
    // Show up to 4 most common status values
    Object.entries(counts)
      .sort((a, b) => b[1] - a[1])
      .slice(0, 4)
      .forEach(([status, count]) => {
        const label = status.charAt(0).toUpperCase() + status.slice(1)
        summary.push({ label, value: count })
      })
  }

  // Currency totals
  columns
    .filter(c => c.type === "currency")
    .slice(0, 2) // at most 2 currency totals
    .forEach(col => {
      const total = data.reduce((sum, row) => {
        return sum + (parseFloat(row[col.dataKey]) || 0)
      }, 0)
      summary.push({
        label: `Total ${col.header}`,
        value: `\u20B9${total.toLocaleString("en-IN", { minimumFractionDigits: 2 })}`,
      })
    })

  return summary.slice(0, 8) // cap at 8 pills (2 rows of 4)
}

export function ExportButton({
  filename,
  title,
  subtitle,
  columns,
  data,
  onExport,
  onExportStart,
  onExportEnd,
  generatedBy,
  summary,
}: ExportButtonProps) {
  const [isExporting, setIsExporting] = useState(false)

  useEffect(() => {
    logger.log(`[v0] [${title}] ExportButton Mounted`, { filename, isExporting })
  }, [title, filename, isExporting])

  const handleExport = async () => {
    if (isExporting) return
    setIsExporting(true)
    onExportStart?.()

    const toastId = toast.loading("📊 Fetching data, please wait...")

    try {
      let exportData = data || []

      if (onExport) {
        exportData = await onExport()
      }

      if (!exportData || exportData.length === 0) {
        toast.dismiss(toastId)
        toast.error("No data available to export")
        setIsExporting(false)
        return
      }

      toast.loading("🖨️ Generating premium PDF report...", { id: toastId })

      // Small delay for smooth toast transition
      await new Promise(resolve => setTimeout(resolve, 400))

      // Build auto summary if caller didn't provide one
      const effectiveSummary = summary ?? buildAutoSummary(exportData, columns)

      exportToPDF({
        filename,
        title,
        subtitle,
        columns,
        data: exportData,
        summary: effectiveSummary,
        generatedBy,
      })

      toast.success(
        `✅ PDF downloaded successfully! (${exportData.length} records)`,
        { id: toastId }
      )
    } catch (error) {
      logger.error("Export failed:", error)
      toast.error("❌ Export failed. Please try again.", { id: toastId })
    } finally {
      setIsExporting(false)
      onExportEnd?.()
    }
  }

  return (
    <Button
      variant="outline"
      className="gap-2 shadow-sm border-primary/20 hover:border-primary/50 transition-all font-semibold"
      disabled={isExporting}
      onClick={() => handleExport()}
    >
      {isExporting ? (
        <Loader2 className="h-4 w-4 animate-spin text-primary" />
      ) : (
        <Download className="h-4 w-4 text-primary" />
      )}
      {isExporting ? "Exporting PDF..." : "Export to PDF"}
    </Button>
  )
}
