import jsPDF from "jspdf"
import autoTable from "jspdf-autotable"
import * as XLSX from "xlsx"
import { logger } from "./logger"

interface ExportColumn {
  header: string
  dataKey: string
  type?: "text" | "number" | "currency" | "date"
}

interface ExportOptions {
  filename: string
  title: string
  subtitle?: string
  columns: ExportColumn[]
  data: any[]
}

/**
 * Format values for professional display
 */
const formatExportValue = (value: any, type?: string) => {
  if (value === null || value === undefined) return ""
  
  switch (type) {
    case "currency":
      return `₹${Number(value).toLocaleString('en-IN', { minimumFractionDigits: 2 })}`
    case "number":
      return Number(value).toLocaleString('en-IN')
    case "date":
      try {
        return new Date(value).toLocaleDateString('en-GB', {
          day: '2-digit',
          month: 'short',
          year: 'numeric',
          hour: '2-digit',
          minute: '2-digit'
        })
      } catch (e) {
        return value.toString()
      }
    default:
      return value.toString()
  }
}

/**
 * Generate and download a PDF report
 */
export const exportToPDF = ({ filename, title, subtitle, columns, data }: ExportOptions) => {
  logger.log(`[export-utils] Starting PDF Export: ${filename}`, { title, columnsCount: columns.length, dataCount: data.length });
  const doc = new jsPDF()
  const now = new Date().toLocaleString('en-GB', {
    day: '2-digit',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  })

  // Company Header
  doc.setFontSize(22)
  doc.setTextColor(0, 80, 158) // Deep Professional Blue
  doc.setFont("helvetica", "bold")
  doc.text("Prozync Innovations", 20, 20)
  
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.setFont("helvetica", "normal")
  doc.text("SmartERP - Enterprise Solutions", 20, 26)
  
  // Right side header info
  doc.setFontSize(9)
  doc.text(`Report: ${title}`, 190, 20, { align: "right" })
  doc.text(`Generated: ${now}`, 190, 25, { align: "right" })

  // Horizontal separator
  doc.setDrawColor(0, 80, 158)
  doc.setLineWidth(0.5)
  doc.line(20, 32, 190, 32)

  // Subtitle/Context
  if (subtitle) {
    doc.setFontSize(11)
    doc.setTextColor(50, 50, 50)
    doc.setFont("helvetica", "bold")
    doc.text(subtitle, 20, 42)
  }

  // Table
  autoTable(doc, {
    startY: subtitle ? 48 : 38,
    head: [columns.map(col => col.header)],
    body: data.map(item => columns.map(col => formatExportValue(item[col.dataKey], col.type))),
    headStyles: {
      fillColor: [0, 80, 158],
      textColor: [255, 255, 255],
      fontSize: 10,
      fontStyle: "bold",
      halign: "left",
      cellPadding: 4
    },
    bodyStyles: {
      fontSize: 9,
      textColor: [40, 40, 40],
      cellPadding: 4
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252] // Light slate background for zebra
    },
    columnStyles: columns.reduce((acc, col, index) => {
      if (col.type === "number" || col.type === "currency") {
        acc[index] = { halign: "right" }
      }
      return acc
    }, {} as any),
    margin: { left: 20, right: 20 },
    didDrawPage: (data) => {
      // Footer
      const pageSize = doc.internal.pageSize
      const pageHeight = pageSize.height ? pageSize.height : pageSize.getHeight()
      
      doc.setFontSize(8)
      doc.setTextColor(150, 150, 150)
      doc.setFont("helvetica", "italic")
      doc.text("Generated by SmartERP | Prozync Innovations Confidential", 20, pageHeight - 10)
      
      const str = `Page ${data.pageNumber}`
      doc.text(str, 190, pageHeight - 10, { align: "right" })
    }
  })

  logger.log("[export-utils] PDF structure completed. Saving file...");
  doc.save(`${filename}.pdf`)
  logger.log("[export-utils] PDF doc.save() called.");
}

/**
 * Generate and download an Excel spreadsheet
 */
export const exportToExcel = ({ filename, title, columns, data }: ExportOptions) => {
  logger.log(`[export-utils] Starting Excel Export: ${filename}`, { title, columnsCount: columns.length, dataCount: data.length });
  // Map data to match headers and format values
  const worksheetData = data.map(item => {
    const row: any = {}
    columns.forEach(col => {
      row[col.header] = formatExportValue(item[col.dataKey], col.type)
    })
    return row
  })

  // Create worksheet
  const worksheet = XLSX.utils.json_to_sheet(worksheetData)
  
  // Set column widths
  const wscols = columns.map(col => ({ 
    wch: Math.max(col.header.length, 15) 
  }))
  worksheet["!cols"] = wscols

  // Create workbook and append sheet
  const workbook = XLSX.utils.book_new()
  XLSX.utils.book_append_sheet(workbook, worksheet, title.substring(0, 31))

  logger.log("[export-utils] Excel structure completed. Saving file...");
  // Generate and download
  XLSX.writeFile(workbook, `${filename}.xlsx`)
  logger.log("[export-utils] Excel XLSX.writeFile() called.");
}
