/**
 * lib/whatsappShare.ts
 * Helper utility for generating formatted WhatsApp sharing deep-links for Invoices, Jobs, and Breakdown alerts.
 */

export interface InvoiceShareData {
  customerName: string
  customerPhone?: string
  invoiceNumber: string
  totalAmount: number | string
  dueDate?: string
  pdfUrl?: string
  paymentLink?: string
}

export interface JobShareData {
  jobTitle: string
  customerName?: string
  customerPhone?: string
  status: string
  assignedTo?: string
  machineName?: string
}

export interface BreakdownAlertData {
  machineName: string
  alarmCode?: string
  severity: "critical" | "warning" | "info" | string
  customerName?: string
  phone?: string
  assignedEngineer?: string
}

/**
 * Clean and format Indian / International phone numbers for WhatsApp
 */
export function formatWhatsAppPhone(phone?: string): string {
  if (!phone) return ""
  let cleaned = phone.replace(/\D/g, "")
  // If 10 digits (standard Indian mobile), prepend country code 91
  if (cleaned.length === 10) {
    cleaned = "91" + cleaned
  }
  return cleaned
}

/**
 * Generate a 1-click WhatsApp share link for an Invoice
 */
export function getInvoiceWhatsAppUrl(data: InvoiceShareData): string {
  const formattedPhone = formatWhatsAppPhone(data.customerPhone)
  const amountStr = typeof data.totalAmount === "number" ? `₹${data.totalAmount.toLocaleString("en-IN")}` : `₹${data.totalAmount}`
  
  let msg = `*INVOICE: ${data.invoiceNumber}*\n`
  msg += `Dear ${data.customerName || "Customer"},\n\n`
  msg += `Your invoice *#${data.invoiceNumber}* for *${amountStr}* has been generated by SmartERP.\n`
  
  if (data.dueDate) {
    msg += `📅 *Due Date:* ${new Date(data.dueDate).toLocaleDateString()}\n`
  }
  if (data.pdfUrl) {
    msg += `📄 *Download Invoice PDF:* ${data.pdfUrl}\n`
  }
  if (data.paymentLink) {
    msg += `💳 *Pay Online Securely:* ${data.paymentLink}\n`
  }
  
  msg += `\nThank you for your business!`
  
  const encoded = encodeURIComponent(msg)
  return formattedPhone ? `https://wa.me/${formattedPhone}?text=${encoded}` : `https://wa.me/?text=${encoded}`
}

/**
 * Generate a 1-click WhatsApp share link for a Job Update
 */
export function getJobWhatsAppUrl(data: JobShareData): string {
  const formattedPhone = formatWhatsAppPhone(data.customerPhone)
  
  let msg = `*SmartERP Job Update*\n`
  msg += `📌 *Job:* ${data.jobTitle}\n`
  msg += `📊 *Status:* ${data.status.toUpperCase()}\n`
  if (data.machineName) msg += `⚙️ *Machine:* ${data.machineName}\n`
  if (data.assignedTo) msg += `👷 *Engineer:* ${data.assignedTo}\n`
  msg += `\nTrack your service live on the SmartERP Customer Portal.`
  
  const encoded = encodeURIComponent(msg)
  return formattedPhone ? `https://wa.me/${formattedPhone}?text=${encoded}` : `https://wa.me/?text=${encoded}`
}

/**
 * Generate a 1-click WhatsApp share link for a Critical Breakdown Alert
 */
export function getBreakdownWhatsAppUrl(data: BreakdownAlertData): string {
  const formattedPhone = formatWhatsAppPhone(data.phone)
  
  let msg = `🚨 *URGENT CNC BREAKDOWN ALERT*\n`
  msg += `⚙️ *Machine:* ${data.machineName}\n`
  msg += `🔥 *Severity:* ${data.severity.toUpperCase()}\n`
  if (data.alarmCode) msg += `⚠️ *Alarm Code:* ${data.alarmCode}\n`
  if (data.assignedEngineer) msg += `👷 *Assigned Engineer:* ${data.assignedEngineer}\n`
  msg += `\nPlease initiate remote diagnosis or field dispatch immediately in SmartERP.`
  
  const encoded = encodeURIComponent(msg)
  return formattedPhone ? `https://wa.me/${formattedPhone}?text=${encoded}` : `https://wa.me/?text=${encoded}`
}
